### ISSUE TITLE
貌似稳定性比py版本差很多，跑了下并发200条线程的http请求没多久就挂掉了，多次复现

### ISSUE THREAD

**Issue by tuhaolam** [ring04h/wyproxy2#2]
go版本: 1.13.6 
机器未见cpu或内存高的现象。
-----
fatal error: concurrent map writes

goroutine 43403 [running]:
runtime.throw(0x79c7c6, 0x15)
        /usr/lib/golang/src/runtime/panic.go:774 +0x72 fp=0xc0001c3950 sp=0xc0001c3920 pc=0x42eb52
runtime.mapdelete_fast64(0x7269c0, 0xc0000135f0, 0x1f73)
        /usr/lib/golang/src/runtime/map_fast64.go:281 +0x302 fp=0xc0001c3998 sp=0xc0001c3950 pc=0x412f42
main.handleResponse(0xc000490090, 0xc000375740, 0x0)
        /home/mqq/user/tulliuslin/scanner/wyproxy2/wyproxy.go:285 +0x140 fp=0xc0001c3c68 sp=0xc0001c3998 pc=0x6dc730
github.com/elazarl/goproxy.FuncRespHandler.Handle(0x7b1db8, 0xc000490090, 0xc000375740, 0x10)
        /root/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20201021153353-00ad82a08272/actions.go:35 +0x3a fp=0xc0001c3c90 sp=0xc0001c3c68 pc=0x6b4e9a
github.com/elazarl/goproxy.(*ProxyConds).Do.func1(0xc000490090, 0xc000375740, 0x0)
        /root/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20201021153353-00ad82a08272/dispatcher.go:300 +0x142 fp=0xc0001c3cf8 sp=0xc0001c3c90 pc=0x6bc132
github.com/elazarl/goproxy.FuncRespHandler.Handle(0xc00000faa0, 0xc000490090, 0xc000375740, 0x10)
        /root/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20201021153353-00ad82a08272/actions.go:35 +0x3a fp=0xc0001c3d20 sp=0xc0001c3cf8 pc=0x6b4e9a
github.com/elazarl/goproxy.(*ProxyHttpServer).filterResponse(0xc0000a5360, 0xc000490090, 0xc000375740, 0xc0001c3f08)
        /root/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20201021153353-00ad82a08272/proxy.go:75 +0x8d fp=0xc0001c3d68 sp=0xc0001c3d20 pc=0x6b8a9d
github.com/elazarl/goproxy.(*ProxyHttpServer).handleHttps.func2(0x813d60, 0xc0001160b0, 0xc0003c6900, 0xc0003f1e60, 0xc00031c400, 0xc0000a5360, 0x8111a0, 0xc0001420e0)
        /root/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20201021153353-00ad82a08272/https.go:239 +0x5d3 fp=0xc0001c3fa0 sp=0xc0001c3d68 pc=0x6bc963
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0001c3fa8 sp=0xc0001c3fa0 pc=0x45b041
created by github.com/elazarl/goproxy.(*ProxyHttpServer).handleHttps
        /root/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20201021153353-00ad82a08272/https.go:190 +0x53c

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7f1811ed3e58, 0x72, 0x0)
        /usr/lib/golang/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0000fa298, 0x72, 0x0, 0x0, 0x797869)
        /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0000fa280, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/internal/poll/fd_unix.go:384 +0x1f8
net.(*netFD).accept(0xc0000fa280, 0xc000678cc8, 0x66fcb4, 0xc0000f2260)
        /usr/lib/golang/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc00000fac0, 0x5ffb45f1, 0xc000678cc8, 0x483fc6)
        /usr/lib/golang/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00000fac0, 0xc000678d18, 0x18, 0xc000000180, 0x66f664)
        /usr/lib/golang/src/net/tcpsock.go:261 +0x47
net/http.(*Server).Serve(0xc0000f21c0, 0x810ee0, 0xc00000fac0, 0x0, 0x0)
        /usr/lib/golang/src/net/http/server.go:2896 +0x280
net/http.(*Server).ListenAndServe(0xc0000f21c0, 0xc0000f21c0, 0x7b1db8)
        /usr/lib/golang/src/net/http/server.go:2825 +0xb7
net/http.ListenAndServe(...)
        /usr/lib/golang/src/net/http/server.go:3081
main.main()
        /home/mqq/user/tulliuslin/scanner/wyproxy2/wyproxy.go:350 +0x3d4

**Comment by ring04h** [comment]
用这个更新的
https://github.com/ring04h/iproxy
