### ISSUE TITLE
一开始没用自带的goproxy/mysql，用了github远程下载的方式，换用自带的之后启动报错

### ISSUE THREAD

**Issue by tuhaolam** [ring04h/wyproxy2#3]
panic: Error parsing builtin CA x509: RSA key missing NULL parameters

goroutine 1 [running]:
goproxy.init.0()
        /root/go/src/goproxy/certs.go:10 +0x194

**Comment by ring04h** [comment]
https://github.com/ring04h/iproxy 使用这个

**Comment by tuhaolam** [comment]
ok, thx~
